# Assignment 2A
# Makefile for compiling and linking Assignment 2A executable.

# Compile TestBiMap
TestBiMap: TestBiMap.cpp BiMap.h
	g++ -Wall -std=c++11 TestBiMap.cpp -o TestBiMap

# Build target
all: TestBiMap

# Clean up executable
clean:
	rm -f TestBiMap