# Assignment 4
# Makefile for compiling and running a4.cpp

# Define the target executable and its dependencies
a4: a4.cpp AvlTree.h BinarySearchTree.h SplayTree.h
	g++ -Wall a4.cpp -o a4

# Compile
all: a4

# Run
run: a4
	./a4

# Clean up
clean:
	rm -f a4