# Assignment 3A
# Makefile for compiling and linking Assignment 3A executable.

# Compile TestIndPQ
TestIndPQ: TestIndPQ.cpp IndPQ.h
	g++ -Wall -std=c++11 TestIndPQ.cpp -o TestIndPQ

# Build target
all: TestIndPQ

# Clean up executable
clean:
	rm -f TestIndPQ